# Generated by Django 2.2 on 2019-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('url', models.CharField(default='javascript:;', max_length=512, verbose_name='链接地址')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='父id')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单管理',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, verbose_name='Key')),
                ('value', models.CharField(db_index=True, max_length=2048, verbose_name='Value')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置管理',
            },
        ),
    ]
