# Generated by Django 2.2 on 2019-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.CharField(max_length=2048, verbose_name='Value'),
        ),
    ]
