# Generated by Django 2.2 on 2019-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='contact',
            field=models.CharField(max_length=32, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='links',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='links',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
