# Generated by Django 2.2 on 2019-07-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190701_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': '导航菜单', 'verbose_name_plural': '导航菜单'},
        ),
    ]
