# Generated by Django 2.2 on 2019-07-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名')),
                ('alias', models.CharField(db_index=True, help_text='url连接名', max_length=128, verbose_name='别名')),
                ('sort', models.IntegerField(default=0, help_text='越小排越前', verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=256, null=True, verbose_name='摘要')),
                ('cover', models.CharField(blank=True, max_length=512, null=True, verbose_name='封面')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.CharField(blank=True, max_length=128, null=True, verbose_name='标签')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Category')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
            },
        ),
    ]
