# Generated by Django 2.2 on 2019-07-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('cms', '0008_category_home_display'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='category',
        #     name='home_display',
        #     field=models.BooleanField(default=False, help_text='首页显示文章', verbose_name='首页显示'),
        # ),
    ]
