# Generated by Django 2.2 on 2019-07-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_article_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_display',
            field=models.BooleanField(default=True, help_text='首页显示文章', verbose_name='首页显示'),
        ),
    ]
