# Generated by Django 2.2 on 2019-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='side',
            field=models.BooleanField(default=True, verbose_name='显示右侧边栏'),
        ),
    ]
