# Generated by Django 2.2 on 2019-07-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_page_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='关键字'),
        ),
    ]
