# Generated by Django 2.2 on 2019-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190705_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
