# Generated by Django 2.2 on 2019-07-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_page_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.IntegerField(choices=[(0, '电脑'), (1, '手机')], default=0, verbose_name='页面类型'),
        ),
        migrations.AlterField(
            model_name='page',
            name='side',
            field=models.BooleanField(default=True, help_text='该值在手机版无效', verbose_name='显示右侧边栏'),
        ),
    ]
